//We recommend that you use Salesforce Connect if most of these conditions apply.
    //You have a large amount of data that you don’t want to copy into your Salesforce org.
    //You need small amounts of data at any one time.
    //You need real-time access to the latest data.
    //You store your data in the cloud or in a back-office system, but want to display or process that data in your Salesforce org.
// Accessing an external object fetches the data from the external system in real time.

//https://trailhead.salesforce.com/en/content/learn/modules/lightning_connect/lightning_connect_introduction

//How to connect
    //OData 2.0 adapter or OData 4.0 adapter
    //Cross-org adapter
    //Custom adapter created via Apex
    //develop your own adapter with the Apex Connector Framework.

public with sharing class SalesforceConnect {
    public SalesforceConnect() {

    }
}
